server:
  port: 8083
spring:
  application:
    name: notification
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  profiles:
    active: default
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key



































#spring.application.name=notification
#
#server.port=8083
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/notification
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#spring.zipkin.base-url=http://localhost:9411
#
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#
##RabbitMQ settings
#rabbitmq.host=localhost
#rabbitmq.port=5672
##spring.rabbitmq.username=guest
##spring.rabbitmq.password=guest
#rabbitmq.exchanges.internal=internal.exchange
#rabbitmq.queue.notification=notification.queue
#rabbitmq.routingkeys.internal-notification=internal.notification.routing-key




